# Generated by Django 6.0.4 on 2026-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_members_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='last_name', max_length=30),
        ),
    ]
