# Generated by Django 6.0.4 on 2026-04-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_member_first_name_member_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
