# Generated by Django 6.0.4 on 2026-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_member_first_name_alter_member_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='add task here', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
